function createfigure
%CREATEFIGURE

%  Auto-generated by MATLAB on 27-Oct-2023 12:16:33

% Create figure
figure('Tag','MLearnAppExportedConfusionMatrixPlot',...
    'Name','Validation Confusion Matrix');

